---
  - name: PHP installation
    apt:
      pkg:
        - php
        - libapache2-mod-php
        - php-mysql
      state: present

  - name: Delete apache2 custom site
    file:
      path: /var/www/html/index.html
      state: absent

  - name: uncomment module php_pdo
      replace:
        path: /etc/php/7.0/apache2/php.ini
        regexp: ';extension=php_pdo_mysql.dll'
        replace: 'extension=php_pdo_mysql.dll'
...