---
- name: Copy MySQL configuration
  template:
    src: my.cnf.j2
    dest: '/etc/mysql/my.cnf'
    owner: root
    group: root
    mode: '0644'
  notify: restart mysql

- name: Copy database dump file
  copy:
    src: templates/vm2.sql
    dest: /tmp
  notify: restart mysql

- name: Restore database
  mysql_db:
    name: vm2
    state: import
    target: /tmp/vm2.sql

- name: Bind to all interfaces
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: bind-address = 0.0.0.0
  notify: restart mysql

- name: Copy .my.cnf
  template:
    src: '.my.cnf.j2'
    dest: '/root/.my.cnf'
    owner: root
    group: root
    mode: '0600'

- name: Set root password
  mysql_user:
    name: root
    host: '{{ item }}'
    password: '{{ mysql_root_password | mandatory }}'
    state: present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'
  no_log: true

- name: Create web user
  mysql_user:
    name: web
    host: '{{ item }}'
    password: '{{ mysql_web_password | mandatory }}'
    priv: 'vm2.Klant:SELECT'
  with_items:
    - '192.168.33.10'
    - '10.0.1.11'
    - 'localhost'
    - '127.0.0.1'
    - '::1'
  no_log: true

