# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]

  config.vm.define "klant1-Test-webserver01" do |webserver|
    webserver.vm.box = "ubuntu/xenial32"
    webserver.vm.hostname = "klant1-prod-webserver01"
    webserver.vm.network "private_network", ip: "192.168.33.10"
    webserver.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    webserver.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = "klant1-prod-webserver01"
    end
  end
  config.vm.define "klant1-Test-webserver02" do |webserver2|
    webserver2.vm.box = "ubuntu/xenial32"
    webserver2.vm.hostname = "klant1-prod-webserver02"
    webserver2.vm.network "private_network", ip: "192.168.33.11"
    webserver2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    webserver2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = "klant1-prod-webserver02"
    end
  end
  config.vm.define "klant1-Test-loadbalancer" do |loadbalancer|
    loadbalancer.vm.box = "ubuntu/xenial32"
    loadbalancer.vm.hostname = "klant1-prod-loadbalancer"
    loadbalancer.vm.network "private_network", ip: "192.168.33.12"
    loadbalancer.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    loadbalancer.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = "klant1-Test-loadbalancer"
    end
  end
  config.vm.define "klant1-Test-database" do |db|
      db.vm.box = "ubuntu/xenial32"
      db.vm.hostname = "klant1-prod-database"
      db.vm.network "private_network", ip: "192.168.33.13"
      db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.gui = false
        vb.name = "klant1-prod-database"
      end
    end
end
