# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

CUSTWEB="{CUSTOMER_ID}-prod-webserver01"
CUSTWEB2="{CUSTOMER_ID}-prod-webserver02"
CUSTLB="{CUSTOMER_ID}-prod-loadbalancer"
CUSTDB="{CUSTOMER_ID}-prod-database"
WEB="{ID}10"
WEB2="{ID}11"
LB="{ID}12"
DB="{ID}13"


Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa","~/.vagrant.d/insecure_private_key"]

  config.vm.define CUSTWEB do |webserver|
    webserver.vm.box = "ubuntu/xenial32"
    webserver.vm.hostname = CUSTWEB
    webserver.vm.network "private_network", ip: WEB
    webserver.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    webserver.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = CUSTWEB
    end
  end
  config.vm.define CUSTWEB2 do |webserver2|
    webserver2.vm.box = "ubuntu/xenial32"
    webserver2.vm.hostname = CUSTWEB2
    webserver2.vm.network "private_network", ip: WEB2
    webserver2.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    webserver2.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = CUSTWEB2
    end
  end
  config.vm.define CUSTLB do |loadbalancer|
    loadbalancer.vm.box = "ubuntu/xenial32"
    loadbalancer.vm.hostname = CUSTLB
    loadbalancer.vm.network "private_network", ip: LB
    loadbalancer.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    loadbalancer.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.gui = false
      vb.name = CUSTLB
    end
  end
  config.vm.define CUSTDB do |db|
      db.vm.box = "ubuntu/xenial32"
      db.vm.hostname = CUSTDB
      db.vm.network "private_network", ip: DB
      db.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.gui = false
        vb.name = CUSTDB
      end
    end
end
