---
- name: Common
  hosts: all
  become: true

  roles:
    - common

- name: Webserver deployment
  hosts: webservers
  become: true

  roles:
    - webservers

- name: Databaseserver deployment
  hosts: database
  become: true

  roles:
    - database


- name: loadbalancer deployment
  hosts: loadbalancer
  become: true

  roles:
    - loadbalancer


...